### ISSUE TITLE
分割不可・右揃えなどのスタイルのクラスを

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1088]
スタイルシートに以下のものを追加することを提案します。

```css
.bold {
  font-weight: bold;
}

.normal-weight {
  font-weight: normal;
}

.right {
  text-align: right;
}

.center {
  text-align: center;
}

.nowrap {
  white-space: nowrap;
}

.display-none {
  display: none;
}
```

理由は次の通りです。

ビューを改善するプルリクエストを作ろうとしたり，あるいは自館の都合に合わせてビューをカスタマイズしたいとします。
スタイルの変更が必要な場合もありますが，スタイルシートを修正するのは憚られることが多いと思います。
スタイルシートは綿密な全体計画のもとにメンテナンスしなければたちまち破綻するからです。また，カスタマイズの場合は Enju のバージョンアップによって破綻する恐れがあります。

しかし，

```html
<td style="white-space: nowrap">
```

のような修正は望ましくありません。

そこで，「太字」「分割不可」「中央揃え」「右揃え」「非表示」のような一般的かつ頻出するスタイルを覚えやすい単純な名前のクラスにしたいわけです。

そうすれば #1024 で示された「いらない検索項目を削除したいというニーズ」に対しても，該当の `<tr>` 要素に `display-none` クラスを付けるだけで済みます。
