### ISSUE TITLE
1.2系の新規インストールでPostgreSQLでは、できません。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1091]
#1061 を確認しようとやってみました。
ついでにPostgreSQLで試してみました。

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ sudo su postgres -c createuser vagrant
createuser: creation of new role failed: ERROR:  role "postgres" already exists
↑ログインアカウントとあったので、vagrant としてみましたができませんでした。

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ sudo su postgres -c createuser yourdbuser
createuser: creation of new role failed: ERROR:  role "postgres" already exists
 ↑ yourdbuser でもできませんでした。

----
参考情報：

1.1.0用の仮想マシンを使って、

$ sudo stop enju
$ mv enju enju.org

とやったあとにためしてみました。

### sudo gem install rails にしました。

$ gem install rails
Fetching: activesupport-4.2.5.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.2.0 directory.

って出たので、

$ sudo gem install rails

ってしました。

###  sudo apt-get update  が必要でした。

$ sudo apt-get update

↑が必要なようでした。
その後↓を実行するとうまくいきました。

$ sudo apt-get install postgresql libpq-dev

**Comment by nabeta** [comment]
コマンドを修正しました。
https://github.com/next-l/enju_leaf/wiki/Install#データベースの設定

**Comment by yegusa** [comment]
> PostgreSQLのユーザを追加します。以下の例では、ログイン中のユーザ名をyourdbuserとしています。

これ、 vagrant ですよね?

**Comment by nabeta** [comment]
そうです。

**Comment by yegusa** [comment]
vagrant を例としたなら、

 $ vi config/database.yml

で、

```
production:
  <<: *default
  database: your_enju_production
  username: vagrant # ここを vagrant に変更する
  password: <%= ENV['YOUR_ENJU_DATABASE_PASSWORD'] %>
```

がいりませんか?
