### ISSUE TITLE
Vagrant による 1.3.4 のインストールに失敗

### ISSUE THREAD

**Issue by tsunekawa** [next-l/enju_leaf#1573]
以下のドキュメントに従ってVagrant経由でEnju Leaf 1.3.4をVirtualBoxのVMにインストールしようとしたところ、Step3で gem が command not found になり、rails プロジェクトが生成されません。

https://github.com/next-l/enju_leaf/wiki/Vagrant

ログは以下の通りです。なお、インストール先のホストPCはWindows10、VirtualBoxのバージョンは6.1です。

```
default: step2 : install solr
default: Solr requires java, please install or set JAVA_HOME properly
default: step3 : install enju_leaf
default: /tmp/vagrant-shell: line 36: gem: command not found
default: /tmp/vagrant-shell: line 37: gem: command not found
default: /tmp/vagrant-shell: line 38: gem: command not found
default: bash: rails: command not found
default: /tmp/vagrant-shell: line 40: cd: enju: No such file     default: No passwd entry for user 'solr'
default: step4 : setup enju_leaf
default: bash: bundle: command not found
default: bash: rails: command not found
default: /tmp/vagrant-shell: line 50: bundle: command not found
default: bash: rails: command not found
default: bash: rails: command not found
default: bash: whenever: command not found
default: /tmp/vagrant-shell: line 59: foreman: command not found
default: Failed to enable unit: Unit file enju_leaf.target does not exist.
default: bash: bundle: command not found
default: step5 : setup web server
default: step6 : cleaning
default: Reading package lists...
default: Building dependency tree...
default: Reading state information...
default: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
default: dd: error writing '/EMPTY': No space left on device
default: 61699+0 records in
default: 61698+0 records out
default: 64695050240 bytes (65 GB, 60 GiB) copied, 152.79 s, 423 MB/s
default: setup completed.
```

この事象について、他の方も再現されますでしょうか？

**Comment by nabeta** [comment]
手元の環境では、以下のエラーになりました。mimemagicでエラーが出ているので、ライセンス問題によるgemの取り下げが関係していると思われます。
https://techracho.bpsinc.jp/hachi8833/2021_03_29/106286

```
    default: Successfully installed actioncable-5.2.4.3
    default: Building native extensions. This could take a while...
    default: ERROR:  Error installing rails:
    default: 	ERROR: Failed to build gem native extension.
    default: 
    default:     current directory: /var/lib/gems/2.5.0/gems/mimemagic-0.3.10/ext/mimemagic
    default: /usr/bin/ruby2.5 -rrubygems /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake RUBYARCHDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/mimemagic-0.3.10 RUBYLIBDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/mimemagic-0.3.10
    default: /usr/bin/ruby2.5: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake (LoadError)
    default: 
    default: rake failed, exit code 1
    default: 
    default: Gem files will remain installed in /var/lib/gems/2.5.0/gems/mimemagic-0.3.10 for inspection.
    default: Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/mimemagic-0.3.10/gem_make.out
```

インストール用のテンプレートを修正したので、これでもう一度試してみます。
https://gist.github.com/nabeta/d01d825374f8284272f22c3962447a19/revisions#diff-136480ea0346f43f3162b9e5501e9878ee81c68c45840e8816d0040d9d691fba
