### ISSUE TITLE
heroku run rake environment sunspot:reindex でエラー

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#453]
```
$ heroku run rake environment sunspot:reindex
Running `rake environment sunspot:reindex` attached to terminal... up, run.
Error using progress bar: Max must be a positive integer
```

Gemfileは

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


gem "enju_leaf", "~> 1.1.0.rc15"
gem "enju_flower", "~> 0.1.0.pre20"
gem "enju_ndl", "~> 0.1.0.pre34"
gem "enju_circulation", "~> 0.1.0.pre40"
gem "enju_subject", "~> 0.1.0.pre28"
gem "charlock_holmes", platforms: :mri
gem "exception_notification", "~> 4.0"
gem "exception_notification-rake"
gem "whenever", require: false
gem "foreman"
gem "sunspot_solr", "~> 2.1.1"
gem "progress_bar"
gem "protected_attributes"
gem "non-stupid-digest-assets"
gem "memcachier"
gem "rails_12factor"
```

sunspot.ymlは

```
production:
  solr:
    hostname: host
    port: 8080
    log_level: WARNING
    path: /solr/collection1
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
```
