### ISSUE TITLE
Amazon S3の設定、使い方を文書化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#533]
#513 に関連してマニュアルに追記する。

**Comment by nabeta** [comment]
1.1系でファイルのアップロード先をAmazon S3に変更するには、config/application.yml で以下の設定が必要になります。

```yaml
# access_key_id, secret_access_key, bucketを各自の環境にあわせて変更
# bucketは存在しない場合自動的に作成される
  amazon:
    aws_hostname: ecs.amazonaws.jp
    hostname: www.amazon.co.jp
    access_key_id: REPLACE_WITH_YOUR_AMAZON_ACCESS_KEY
    secret_access_key: REPLACE_WITH_YOUR_AMAZON_SECRET_ACCESS_KEY
    bucket: enju_leaf

# 中略

# storageを :local から :s3 に変更
  uploaded_file:
    storage: :s3
```

1.2系ではこれらの設定は環境変数、もしくは .env ファイルに移動する予定です。
